### ISSUE TITLE
install ridgerunner via homebrew - ./configure fails - cannot find octrope

### ISSUE THREAD

**Issue by muellair** [designbynumbers/homebrew-cantarellalab#1]
I tried installing ridgerunner using Homebrew on Ubuntu. I ran the interactive mode of homebrew's install:
> brew install -i ridgerunner

and then I ran the configure file. The last two lines of the resulting output are:
> checking for library containing octrope... no
> configure: error: ridgerunner requires the plcurve library

Probably the most relevant lines in config.log were:
> configure:13472: checking for library containing octrope
> configure:13502: gcc-11 -o conftest -g -O2   conftest.c -largtable2 -lm  >&5
> /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: /tmp/cckjlhGf.o: in function `main':
> /tmp/ridgerunner-20221009-23533-1xnh6dy/ridgerunner-2.1.1/conftest.c:45: undefined reference to `octrope'
> collect2: error: ld returned 1 exit status
> configure:13502: $? = 1
> configure: failed program was:
...
> configure:13502: gcc-11 -o conftest -g -O2   conftest.c -lplcurve  -largtable2 -lm  >&5
> /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: cannot find -lplcurve: No such file or directory
> collect2: error: ld returned 1 exit status
> configure:13502: $? = 1
> configure: failed program was:
...
> configure:13522: result: no
> configure:13530: error: ridgerunner requires the plcurve library

But Homebrew had installed liblcurve.

Is it possible that it should be "-libplcurve" or "-plcurve" instead of "-lplcurve" in the first line of the second paragraph above?

I am not very familiar with coding, in particular not with C programming or autoconf. So I am sorry if this is a mistake from my side. I've tried to understand the problem for quite a while now. I attached the full config.log and bash output, in case it is in fact a bug.

[config.log.log](https://github.com/designbynumbers/homebrew-cantarellalab/files/9741768/config.log.log)
[bash_output.txt](https://github.com/designbynumbers/homebrew-cantarellalab/files/9741770/bash_output.txt)

**Comment by designbynumbers** [comment]
Hello! This is quite a late response, but I'm adding it for posterity in case anyone else looks here. The short is "yes, you're right". There turned out to be two problems-- on MacOS, the default filesystem is case-insensitive, so -lplcurve linked fine to libplCurve.la (or .so). Not so on Linux. 

After that was fixed, there were a few other downstream issues revealed (mostly that ridgerunner couldn't see a brew installation of plcurve even after it found the library due to some design issues with globals in plcurve (which are now patched in the latest version). 

Everything seems to work on mac and Fedora 34, but we'll continue to test on different Linux systems.
